export const SET_LOADING = 'SET_LOADING';
export const SET_BANNERS = 'SET_BANNERS';
export const SET_PACKAGES = 'SET_PACKAGES';
export const SET_PACKAGE_DETAILS = 'SET_PACKAGE_DETAILS';
export const SET_DELIVERY_TIME_LIST = 'SET_DELIVERY_TIME_LIST';
export const SET_ABOUT_US = 'SET_ABOUT_US';
export const SET_FAQ_LIST = 'SET_FAQ_LIST';
export const SET_AREA_LIST = 'SET_AREA_LIST';
export const SET_DELIVERY_METHOD = 'SET_DELIVERY_METHOD';
export const SET_ADDRESS_ID = 'SET_ADDRESS_ID';
export const SET_ADDRESS = 'SET_ADDRESS';

export const SET_MEAL_LIST_BREAKFAST = 'SET_MEAL_LIST_BREAKFAST';
export const SET_MEAL_LIST_MEAL = 'SET_MEAL_LIST_MEAL';
export const SET_MEAL_LIST_SNACKS = 'SET_MEAL_LIST_SNACKS';
export const SET_MEAL_LIST_SOUP = 'SET_MEAL_LIST_SOUP';

export const SET_END_DATE = 'SET_END_DATE';
export const SET_MY_PACKAGES = 'SET_MY_PACKAGES';
export const SET_MY_MEALS = 'SET_MY_MEALS';
export const SET_DAYS_LIST = 'SET_DAYS_LIST';
export const SET_MEAL_TYPE_LIST_UPGRADE_PACKGE = 'SET_MEAL_TYPE_LIST_UPGRADE_PACKGE';
export const SET_WHY_US = 'SET_WHY_US';
export const SET_COUPON_LIST ='SET_COUPON_LIST';
